
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - postgres
      - neo4j

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname
      - TZ=Asia/Seoul
    command: postgres -c log_timezone=Asia/Seoul -c timezone=Asia/Seoul
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  neo4j:
    image: neo4j:5.11.0
    ports:
      - "7687:7687"
      - "7474:7474"
      - "7473:7473"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_conf:/conf
      - ./init_scripts:/var/lib/neo4j/import 

    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - TZ=Asia/Seoul
      - NEO4J_PLUGINS=["apoc"]

volumes:
  postgres_data:
  neo4j_data:
  neo4j_logs:
  neo4j_conf: